export const MutationTypes = Object.freeze({
  SET_UPCOMING_MEETINGS: "SET_UPCOMING_MEETINGS",
  SET_SELECTED_MEETING: "SET_SELECTED_MEETING",
  SET_SELECTED_PLAN: "SET_SELECTED_PLAN",
  SET_JWT: "SET_JWT",
  SET_USER: "SET_USER"
});
export const ActionTypes = Object.freeze({
  FETCH_UPCOMING_MEETINGS: "FETCH_UPCOMING_MEETINGS",
  SET_MEETING: "SET_MEETING",
  FETCH_MEETING: "FETCH_MEETING",
  FETCH_USER_COMMITTEE_MEETINGS: "FETCH_USER_COMMITTEE_MEETINGS",
  FETCH_PLAN: "FETCH_PLAN",
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT"
});
export const Getters = Object.freeze({
  UPCOMING_MEETINGS: "UPCOMING_MEETINGS",
  SELECTED_MEETING: "SELECTED_MEETING",
  SELECTED_PLAN: "SELECTED_PLAN",
  JWT: "JWT",
  USER: "USER"
});
