export const MutationTypes = Object.freeze({
  SET_UPCOMING_MEETINGS: "SET_UPCOMING_MEETINGS",
  SET_SELECTED_MEETING: "SET_SELECTED_MEETING",
  SET_SELECTED_PLAN: "SET_SELECTED_PLAN"
});
export const ActionTypes = Object.freeze({
  FETCH_UPCOMING_MEETINGS: "FETCH_UPCOMING_MEETINGS",
  SET_MEETING: "SET_MEETING",
  FETCH_MEETING: "FETCH_MEETING",
  FETCH_PLAN: "FETCH_PLAN"
});
